In [1]:
import rasterio
import numpy as np

In [5]:
with rasterio.open("22103_rtp_a1.tif") as src:
    # print(src.crs)
    # print(src.res)
    # print(src.count)
    data = src.read(1)
    # print(data.shape)
    # print(data.min(), data.max())  # value range
    # print(data.dtype)
    print(data)

[[-999999. -999999. -999999. ... -999999. -999999. -999999.]
 [-999999. -999999. -999999. ... -999999. -999999. -999999.]
 [-999999. -999999. -999999. ... -999999. -999999. -999999.]
 ...
 [-999999. -999999. -999999. ... -999999. -999999. -999999.]
 [-999999. -999999. -999999. ... -999999. -999999. -999999.]
 [-999999. -999999. -999999. ... -999999. -999999. -999999.]]


/var/folders/04/s_rk8gfn6vq1608hxwwtl_040000gn/T/ipykernel_6768/1375106753.py:5: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  data = src.read(1)
